VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IErrBuf"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

Property Get Description() As String
End Property

Property Let Description(arg_description As String)
End Property

Property Get Number() As Integer
End Property

Property Let Number(arg_number As Integer)
End Property


Property Get Source() As String
End Property


Property Let Source(arg_source As String)
End Property
